apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "recsys.fullname" . }}-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "recsys.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.backend.persistence.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "recsys.fullname" . }}-mlflow
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "recsys.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.mlflow.persistence.size }}
